#####
### Project Babbage — Services for Local Development
#####
version: '3.8'
networks:
  babnet:
    ipam:
      config:
        - subnet: 172.20.0.0/23

services:

  ###
  ## Standard MetaNet Services
  ###

  byteshop-mysql:
    image: "mysql:8.0"
    platform: linux/x86_64
    hostname: 'byteshop-mysql'
    command: 'mysqld --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync'
    restart: always
    volumes:
     - './data/byteshop-mysql-data:/var/lib/mysql'
    environment:
      MYSQL_HOST: "127.0.0.1"
      MYSQL_TCP_PORT: 3114
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "bytes"
    ports:
      - "3114:3114"
    networks:
      babnet:
        ipv4_address: 172.20.1.3
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10

  ## PHPMyAdmin — Web-based SQL database viewer
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - byteshop-mysql
    environment:
      PMA_HOST: byteshop-mysql
      PMA_PORT: 3114
      PMA_ARBITRARY: 1
    restart: always
    ports:
    - 8090:80
    networks:
    - babnet
      
